name: stock-spyder
on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run static crawler
        run: python static.py

      - name: Run API crawler
        run: python api.py

      - name: Commit & push new data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "GitHub Actions"
          git add static.* api.csv || true
          git diff --cached --quiet && echo "No changes" || \
          (git commit -m "Update data via workflow" && git push origin HEAD:main)
